Repository mrusme/neonmodem, pull requests merged in 2023-06, with the labels that each got.

#19 Switch to using the more up to date go.elara.ws/go-lemmy
  go.mod
  go.sum
  system/lemmy/lemmy.go
Labels: enhancement

#26 Fix #16 (connecting to HN)
  cmd/connect.go
Labels: bug

#33 Fix segfault when entering incorrect password
  cmd/root.go
Labels: bug, enhancement

#38 Optionally hide splash and banner?
  config/config.go
  ui/header/header.go
  ui/views/splash/splash.go
Labels: enhancement

#40 Spinner color from config
  config/config.go
  ui/header/header.go
  ui/theme/theme.go
Labels: enhancement
